services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${SERVER_PORT:-3001}
    ports:
      - "${SERVER_PORT:-3001}:3001" 
    depends_on:
      - mongo
      - redis
    environment:
      - SERVER_PORT=${SERVER_PORT:-3001}
      - MONGODB_URI=mongodb://mongo:27017/users-role-perm
      - REDIS_URL=redis://redis:6379
    networks:
      - crm-network
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - crm-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge



