services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${SERVER_PORT:-3000}
    ports:
    - "${SERVER_PORT:-3000}:3000" 
    depends_on:
      - mongo
    environment:
      - SERVER_PORT=${SERVER_PORT:-3000}
      - MONGODB_URI=mongodb://mongo:27017/users-role-perm
    networks:
      - crm-network
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge